/**
 * @file    espnow_manager.h
 * @author  Mateusz Ressel (https://github.com/matt-ressel)
 * @brief   Public API for the ESP-NOW Radio Manager.
 *
 * @details This component encapsulates the low-level WiFi stack initialization
 *          and ESP-NOW configuration. It exposes the initialization interface
 *          required to set up the device as a dedicated Radio Co-Processor (RCP)
 *          listening on a fixed channel.
 *
 * @version 0.1
 * @date    2025-12-28
 *
 * @copyright Copyright (c) 2025 Mateusz Ressel. Licensed under the MIT License.
 */

#ifndef ESPNOW_MANAGER_H
#define ESPNOW_MANAGER_H

#include <stdint.h>  // Standard integer types (e.g., uint8_t)

#include "esp_err.h"  // For esp_err_t error codes (e.g., ESP_OK)
#include "esp_now.h"  // ESP-NOW specific types (e.g., ESP_NOW_ETH_ALEN)

/** @brief Size of the FreeRTOS queue that buffers incoming ESP-NOW events. */
#define ESPNOW_QUEUE_SIZE 20

/** @brief Stack size in bytes for the ESP-NOW processing task. */
#define ESPNOW_STACK_SIZE 3072  // Adjusted for robust operation

/** @brief Priority for the FreeRTOS task that processes ESP-NOW events. */
#define ESPNOW_TASK_PRIORITY 12

/**
 * @brief Maximum time (in FreeRTOS ticks) to wait for a queue operation.
 *
 * Used to prevent indefinite blocking when sending an event to the queue.
 */
#define ESPNOW_QUEUE_TIMEOUT_TICKS 50

/**
 * @brief Enumeration of ESP-NOW event identifiers.
 *
 * Defines different types of events that can be passed from ESP-NOW callbacks
 * or other sources to the `espnow_task` via its event queue.
 */
typedef enum {
  ESPNOW_RECV_CB, /**< Event generated by the ESP-NOW data receive callback, indicating a new packet has arrived. */
  // Future event types, such as ESPNOW_SEND_CB (for send status), could be added here.
} espnow_event_id_t;

/**
 * @brief Structure holding data associated with an ESP-NOW receive callback event.
 *
 * This structure contains the sender's MAC address and a pointer to a dynamically
 * allocated buffer holding the received data payload, along with its length.
 * The `data` buffer must be freed by the task that processes this event.
 */
typedef struct {
  uint8_t mac_addr[ESP_NOW_ETH_ALEN]; /**< MAC address of the device that sent the data. */
  uint8_t* data;                      /**< Pointer to a dynamically allocated buffer holding the received data. The consumer of this event is responsible for freeing this memory. */
  int8_t rssi;                        /**< RSSI value of the received packet. */
  int data_len;                       /**< Length (in bytes) of the received data payload. */
} espnow_event_recv_cb_t;

/**
 * @brief Union to hold specific information for different ESP-NOW event types.
 *
 * This allows the `espnow_event_t` structure to accommodate various event data formats
 * while maintaining a consistent structure for the event queue.
 */
typedef union {
  espnow_event_recv_cb_t recv_cb; /**< Data specific to an ESP-NOW receive callback event. */
  // Other event-specific structures could be added here, e.g.:
  // espnow_event_send_cb_t send_cb;
} espnow_event_info_t;

/**
 * @brief Main event structure for ESP-NOW communication.
 *
 * This structure is passed through a FreeRTOS queue from the ESP-NOW ISR context
 * to the dedicated processing task (`espnow_task`). It contains an `id` to identify
 * the event type and a `union info` holding the event-specific data.
 */
typedef struct {
  espnow_event_id_t id;     /**< Identifier for the type of ESP-NOW event. */
  espnow_event_info_t info; /**< Union containing the actual event data. */
} espnow_event_t;

/**
 * @brief Initializes the ESP-NOW Manager component.
 *
 * This function sets up the necessary WiFi services, initializes the ESP-NOW
 * stack, registers callbacks, and starts the processing task for handling
 * incoming ESP-NOW events.
 *
 * @return esp_err_t
 *   - ESP_OK: If initialization was successful.
 *   - Other esp_err_t codes on failure (e.g., WiFi or ESP-NOW init errors).
 */
esp_err_t espnow_manager_init(void);

/**
 * @brief Adds or verifies an ESP-NOW peer for encrypted communication.
 *
 * This function registers a peer device, enabling encrypted communication using the
 * LMK (Local Master Key). If the peer already exists in the ESP-NOW peer list,
 * the function returns ESP_OK. This is typically called during initialization
 * (to add peers from NVS) or dynamically (e.g., via MQTT commands).
 *
 * @param peer_addr Pointer to a buffer containing the 6-byte MAC address of the peer.
 *
 * @return esp_err_t
 *   - ESP_OK: If the peer was successfully added or already existed.
 *   - ESP_ERR_INVALID_ARG: If `peer_addr` is NULL.
 *   - Other esp_err_t codes from `esp_now_add_peer` on failure (e.g., peer list full).
 */
esp_err_t add_peer_with_encryption(const uint8_t* peer_addr);

#endif  // ESPNOW_MANAGER_H